# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Player

on:
  push:
    branches: [ ]

permissions:
  contents: read

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        git clone https://github.com/osscameroon/broken_link_checker.git /tmp/blc
        cd /tmp/blc
        git checkout patch
        pip install -r requirements.txt
    - name: Test
      run: |
        python -m blc -D -n -d .5 -b 1 https://osscameroon.com
  blog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        git clone https://github.com/osscameroon/broken_link_checker.git /tmp/blc
        cd /tmp/blc
        git checkout patch
        pip install -r requirements.txt
    - name: Test
      run: |
        python -m blc -D -n -d .5 -b 1 https://blog.osscameroon.com

