# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Player

on:
  push:
    branches: [ ]

permissions:
  contents: read

env:
  CMD: python blc.blc -D -n -d .5

jobs:
  ossblog:
    name: Checking of https://osscameroon.com
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        ./install_deps.sh
    - name: Play
      run: |
        $CMD -b 1 https://osscameroon.com
  osswebsite:
    name: Checking of https://blog.osscameroon.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sh ./install_deps.sh
      - name: Play
        run: |
          $CMD -b 1 https://blog.osscameroon.com

